#!/bin/bash
# This isn't a bash script, but that #! should give
# us pretty highlighting in most editors.


# Files and extensions we usually want to ignore.
# if you're making a new bundle, it's a good idea to
# copy this part.
.*/00readme\.txt
.*/LICENSE\.md
.*/Makefile
.*/README
.*/README.md
.*/readme\.txt
.*/ls-R
.*\.fmt
.*\.log
.*\.lua
.*\.mf
.*\.pl
.*\.ps
/web2c/metafont/mf\.base
# End "always ignore" section.


# Bundle-specific ignore patterns




# A few CSLaTeX files conflict with babel, ignore them for now.
/tex/cslatex/.*
/tex/csplain/.*


# I don't think tectonic has xindy support.
# Ignore for now, causes many conflicts
/xindy/.*

# We may need this, but exclude for now.
# Also causes many conflicts.
/tex4ht/.*

# These require pLaTeX2e, tectonic uses XeTeX
/tex/uplatex/.*
/tex/uptex/.*

# These require LuaLaTeX, tectonic uses XeTeX
/tex/luatex/.*
/tex/lualatex/.*

# Other odd tex formats & unnecessary files
/tex/ptex/.*
/tex/platex/.*
/tex/lollipop/.*
/tex/context/.*
/context/.*
/texdoc/.*
/texdoctk/.*
/texconfig/.*
/scripts/.*
/dvips/.*
/asymptote/.*
/makeindex/.*
/luatex-cache/.*
/hb2gf/.*
/chktex/.*
/source/.*
/doc/.*


# Discontinued project
# (Why is this even in texlive?)
/tex/lambda/.*
/omega/.*


# Currently broken, fix later
/tex/latex/fithesis/.*


# Probably don't need?
# (there's a xelatex alternative)
/tex/xetex/xetex-pstricks/pstricks.con
/tex/generic/pstricks/pstricks.con